app:
    resource: "@AppBundle/Controller/"
    type:     annotation
api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"