# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    api.json_request_content_listener:
        class: 'ApiBundle\EventListener\JsonRequestContentListener'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.login:
        class: 'AppBundle\EventListener\LoginListener'
        arguments: ['@router', '@security.token_storage', '@security.authorization_checker', '@doctrine']
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    api.token_authenticator:
            class: 'ApiBundle\Security\TokenAuthenticator'
            arguments: ['@doctrine.orm.entity_manager']